"""
Writes the Manim code generated by Gemini to a .py file and runs it headlessly.
The generated script calls scene.render() itself.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


def _extract_scene_class_name(code: str) -> str:
    match = re.search(r"class\s+(\w+)\s*\(\s*Scene\s*\)", code)
    if not match:
        raise ValueError("Could not find a Scene subclass in generated Manim code")
    return match.group(1)


def render_scene(manim_code: str, work_dir: str | Path) -> Path:
    # Convert to an absolute path so cwd + script_path can never duplicate it.
    work_dir = Path(work_dir).expanduser().resolve()
    work_dir.mkdir(parents=True, exist_ok=True)

    script_path = work_dir / "generated_scene.py"
    script_path.write_text(manim_code, encoding="utf-8")

    scene_name = _extract_scene_class_name(manim_code)

    # Run using the same Python interpreter/environment as the GitHub Actions job.
    result = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=str(work_dir),
        capture_output=True,
        text=True,
        timeout=600,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Manim render failed:\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}"
        )

    media_root = work_dir / "media" / "videos" / script_path.stem
    candidates = list(media_root.rglob(f"{scene_name}.mp4"))

    if not candidates:
        raise FileNotFoundError(
            f"Rendered mp4 not found under {media_root}.\n"
            f"stdout was:\n{result.stdout}"
        )

    return max(candidates, key=lambda p: p.stat().st_mtime)
